version: '3'
services:
  api:
    image: thecodingmachine/php:8.1-v4-apache
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.example.rule=Host(`example.app.localhost`)
      - traefik.http.routers.example=true
      - traefik.http.routers.example.tls=true
      - traefik.http.routers.example.service=example
      - traefik.http.services.example.loadbalancer.server.port=80
    environment:
      APACHE_DOCUMENT_ROOT: "public/"
      PHP_EXTENSION_XDEBUG: "1"
      PHP_EXTENSION_REDIS: "1"
      PHP_EXTENSION_INTL: "1"
      PHP_EXTENSION_GD: "1"
      PHP_EXTENSION_PGSQL: "1"
      PHP_EXTENSION_PDO_PGSQL: "1"
    volumes:
      - ./repos/example:/var/www/html